### ISSUE TITLE
Unbuild Stub breaks in Vue Vite application

### ISSUE THREAD

**Issue by lvpaspaltzis** [vargasmesh/shining-text#1]
Relates to https://github.com/unjs/unbuild/pull/300

When running `unbuild --stub` in the `vue-shining-text` package, the Vue Playground breaks by raising:

```
[vite] Internal server error: Failed to resolve entry for package "vue-shining-text". The package may have incorrect main/module/exports specified in its package.json.
```

**Comment by lvpaspaltzis** [comment]
That worked, @pi0 ! Thank you!! You said:
> By creating a top level .mjs entry, we can trick vite into resolving .ts (stubbed) files and also have a valid production package.

Why a valid production package must have an `index.mjs` outside of `src`?

**Comment by pi0** [comment]
It is because is shared between stub mode and production. Otherwise you could directly point to `dist/index.mjs`

**Comment by lvpaspaltzis** [comment]
@pi0 thank you for the help! Learned a lot
